import '../../style/bootstrap.css'
import '../../style/style.css'
import '../../style/style_font.css'
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import Footer from "./footer";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>

      <Script src="/js/bootstrap.js"></Script>
      <Script src="/js/wow.js"></Script>
      <Script src="/js/script.js"></Script>
      
    </html>
  );
}
